# Create InfluxDB user

- name: Create an user in InfluxDB
  influxdb_user:
    hostname: "{{ influxdb_hostname }}"
    login_username: "{{ influxdb_admin_user_name }}"
    login_password: "{{ influxdb_admin_user_password }}"
    ssl: "{{ influxdb_enable_ssl }}"
    retries: 0
    validate_certs: "{{ influxdb_ssl_validate_cert }}"
    user_name: "{{ influxdb_user_name }}"
    user_password: "{{ influxdb_user_password }}"
    grants:
      "{{ influxdb_user_grants | default(omit) }}"
    admin: "{{ influxdb_user_admin | default('no') }}"
