---
# Database related steps
#

- name: Create Influx DB
  influxdb_database:
    hostname: "{{ influxdb_hostname }}"
    username: "{{ influxdb_admin_user_name }}"
    password: "{{ influxdb_admin_user_password }}"
    database_name: "{{ influxdb_apimon_db_name }}"
    ssl: yes
    retries: 0
    validate_certs: no
    # "{{ apimon_ssl_validate_cert }}" 

    state: present
